### ISSUE TITLE
Foldersize calculation doesn't work for me

### ISSUE THREAD

**Issue by thomasklemenc** [FrankysWeb/Report-MailboxStatistics#1]
Foldersize is empty for me.
Exchange Server 2016, running the script from an exchange management shell on windows 10.

![OUTLOOK_0VADBQnaUe](https://user-images.githubusercontent.com/6023076/206650602-a794e397-5909-4e93-8ca5-43495952da76.png)

My tests show that the string extraction / calculation doesn't seem to work:

```
[PS] C:\>$mailboxfolderstatistics = Get-MailboxFolderStatistics username | select folderpath,foldersize,itemsinfolder
[PS] C:\> $TopFoldersBySize = $MailboxFolderStatistics | Select-Object FolderPath,@{Name="Foldersize";Expression={$r=$_.FolderSize; [long]$a = ($r.Substring($r.IndexOf("(")+1,($r.Length - 2 - $r.IndexOf("("))) -replace " bytes","" -replace ",","") ; [math]::Round($a/1048576,2) } } | sort foldersize -Descending | select -first $CountTopFolder
>>
Select-Object : Das Argument für den Parameter "First" kann nicht überprüft werden. Das Argument ist NULL oder leer, oder ein Element der Argumentauflistung enthält einen NULL-Wert. Geben Sie eine Auflistung an, die keine NULL-Werte
enthält, und führen Sie dann den Befehl erneut aus.
In Zeile:1 Zeichen:320
+ ... ,2) } } | sort foldersize -Descending | select -first $CountTopFolder
+                                                           ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Select-Object], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.SelectObjectCommand
```
Removing the "select -first":
```
[PS] C:\> $TopFoldersBySize = $MailboxFolderStatistics | Select-Object FolderPath,@{Name="Foldersize";Expression={$r=$_.FolderSize; [long]$a = ($r.Substring($r.IndexOf("(")+1,($r.Length - 2 - $r.IndexOf("("))) -replace " bytes","" -replace ",","") ; [math]::Round($a/1048576,2) } } | sort foldersize -Descending
[PS] C:\>$TopFoldersBySize

FolderPath                                                                  Foldersize
----------                                                                  ----------
/RSS-Abonnements/Frankys Web
/RSS-Abonnements
```

Foldersize in $TopFoldersBySize is always empty

**Comment by thomasklemenc** [comment]
If I replace your expression

`Expression={$r=$_.FolderSize; [long]$a = ($r.Substring($r.IndexOf("(")+1,($r.Length - 2 - $r.IndexOf("("))) -replace " bytes","" -replace ",","") ; [math]::Round($a/1048576,2) } `

with this:

```Expression={ "{0:N2}" -f ((($_.FolderSize -replace "[0-9\.]+ [A-Z]* \(([0-9,]+) bytes\)","`$1") -replace ",","") / 1MB)}```

it works in my environment:

![image](https://user-images.githubusercontent.com/6023076/206652261-f86422a5-6e79-474f-84cf-ea0c161e56d1.png)

**Comment by FrankysWeb** [comment]
Please have a look at the folder sorting (your screenshot). With your fix, folders are not sorted by size. I will check to find a solution for ENG and DE servers

**Comment by FrankysWeb** [comment]
Hi, could you please try this one?
```
@{Name="Foldersize";Expression={[long]$a = "{0:N2}" -f ((($_.FolderSize -replace "[0-9\.]+ [A-Z]* \(([0-9,]+) bytes\)","`$1") -replace ",","")); [math]::Round($a/1048576,2) }}
```

**Comment by thomasklemenc** [comment]
Oh I didn't even check for the sorting, my bad.
Your new one works, tho I would suggest doing this:

`[math]::Round($a/1MB,2)`

instead of this:

`[math]::Round($a/1048576,2)`

for readability

**Comment by FrankysWeb** [comment]
Yes, thanks for you help. I will change this too.
